import LoginPage from "@/components/LoginPage";
import { useGlobalContext } from "@/contexts/GlobalContext";
import GlobalStyle from "@/styles/global";
import { darkTheme, lightTheme } from "@/styles/theme";
import Head from "next/head";
import { ThemeProvider } from "styled-components";

export default function Home() {
  const { theme } = useGlobalContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
        <GlobalStyle />
        <LoginPage />
      </ThemeProvider>
    </>
  );
}
